/// Flutter icons TawakalnaAppIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TawakalnaAppIcons
///      fonts:
///       - asset: fonts/TawakalnaAppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TawakalnaAppIcons {
  TawakalnaAppIcons._();

  static const _kFontFam = 'TawakalnaAppIcons';
  static const String? _kFontPkg = null;

  static const IconData hands_heart = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health_passport = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData id_card = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microscope = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qr_code = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vaccine = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData family_insurance = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
